config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_for(flat) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :picture_url %>
    <%= f.text_field :picture_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_guests %>
    <%= f.number_field :number_of_guests, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price_per_night %>
    <%= f.number_field :price_per_night, class: 'form-control' %>
  </div>
  <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @flats.count %> flats out of our <%= Flat.count %> on our website.</p>
      <% else %>
        <p>All <%= Flat.count %> flats.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div class="flat-card">
          <div class="flat-card-image" style="background-image: url('<%= flat.picture_url %>')"></div>
          <div class="flat-card-content">
            <div class="flat-card-title">
              <h4><%= flat.name %></h4>
            </div>
            <p><%= flat.address %></p>
            <div class="flex">
              <div class="flex">
                <i class="material-icons mr-2">people</i><span><%= flat.number_of_guests %></span>
              </div>
              <div class="flex ml-3">
                <i class="material-icons mr-2">euro_symbol</i> <%= flat.price_per_night %>
              </div>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to 'More info', flat_path(flat) %>
            <%= link_to 'Edit', edit_flat_path(flat), class: 'ml-3 text-warning' %>
            <%= link_to "Remove", flat_path(flat),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: 'ml-3 text-danger'
            %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= render "form", flat: @flat %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('<%= @flat.picture_url %>')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%= @flat.address %>&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C<%= @flat.address %>&key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From:</span>
            <input type="text" class="form-control" placeholder="12/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To:</span>
            <input type="text" class="form-control" placeholder="18/10/2017" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="material-icons mr-2">people</i><span><%= @flat.number_of_guests %></span>
          </div>
          <div class="flex ml-3">
            <i class="material-icons mr-2">euro_symbol</i> <%= @flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fa fa-facebook-square fa-2x mr-2"></i>
            <i class="fa fa-twitter-square fa-2x mr-2"></i>
            <i class="fa fa-pinterest-square fa-2x mr-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Simple Airbnb', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
          <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary my-2 my-sm-0 ml-2' %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>